language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y uuid-dev libxml2-dev libffi-dev lcov

matrix:
  include:
    - compiler: gcc
    - compiler: clang

before_script:  
    - git clone -b 3.7.2 --single-branch https://github.com/cpputest/cpputest.git cpputest-build
    - cd cpputest-build
    - cmake . && make
    - sudo make install 
    - cd ..
    - git clone -b 2.7 --single-branch https://github.com/akheron/jansson.git jansson-build
    - cd jansson-build
    - cmake -DJANSSON_BUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr . && make
    - sudo make install
    - cd ..
    - mkdir build install
    - cd build
    - cmake -DCMAKE_SKIP_BUILD_RPATH=TRUE -DBUILD_DEPLOYMENT_ADMIN=ON -DBUILD_EXAMPLES=ON -DBUILD_LOG_SERVICE=ON -DBUILD_LOG_WRITER=ON -DBUILD_REMOTE_SERVICE_ADMIN=ON -DBUILD_RSA_DISCOVERY_CONFIGURED=ON -DBUILD_RSA_DISCOVERY_ETCD=ON -DBUILD_RSA_DISCOVERY_SHM=ON -DBUILD_RSA_EXAMPLES=ON -DBUILD_RSA_REMOTE_SERVICE_ADMIN_SHM=ON -DBUILD_RSA_REMOTE_SERVICE_ADMIN_HTTP=ON -DBUILD_REMOTE_SHELL=ON -DBUILD_SHELL=ON -DBUILD_SHELL_TUI=ON -DCMAKE_INSTALL_PREFIX=../install ..

script: 
    - make all 
    - make test ARGS="-V"
