language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y uuid-dev libjansson-dev libxml2-dev lcov libffi-dev

matrix:
  include:
    - compiler: gcc
    - compiler: clang

before_script:  
    - git clone -b 3.7.2 --single-branch https://github.com/cpputest/cpputest.git cpputest-build
    - cd cpputest-build
    - cmake . && make
    - sudo make install 
    - cd ..
    - git clone -b 2.7 --single-branch https://github.com/akheron/jansson.git jansson-build
    - cd jansson-build
    - cmake -DJANSSON_BUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr . && make
    - sudo make install
    - cd ..
    - mkdir build install
    - cd build
    - cmake -DBUILD_DEPLOYMENT_ADMIN=ON -DBUILD_EXAMPLES=ON -DBUILD_LOG_SERVICE=ON -DBUILD_LOG_WRITER=ON -DBUILD_REMOTE_SERVICE_ADMIN=ON -DBUILD_RSA_DISCOVERY_CONFIGURED=ON -DBUILD_RSA_DISCOVERY_ETCD=ON -DBUILD_RSA_DISCOVERY_SHM=ON -DBUILD_RSA_EXAMPLES=ON -DBUILD_RSA_REMOTE_SERVICE_ADMIN_SHM=ON -DBUILD_RSA_REMOTE_SERVICE_ADMIN_HTTP=ON -DBUILD_REMOTE_SHELL=ON -DBUILD_SHELL=ON -DBUILD_SHELL_TUI=ON -DBUILD_DEVICE_ACCESS=ON -DBUILD_DEVICE_ACCESS_EXAMPLE=ON -DBUILD_FRAMEWORK_TESTS=OFF -DBUILD_UTILS-TESTS=ON -DCPPUTEST_INCLUDE_DIR=$HOME/cpputest/include -DCPPUTEST_LIBRARY=$HOME/cpputest/lib/libCppUTest.a -DCPPUTEST_EXT_INCLUDE_DIR=$HOME/cpputest/include -DCPPUTEST_EXT_LIBRARY=$HOME/cpputest/lib/libCppUTestExt.a -DENABLE_CODE_COVERAGE=ON -DBUILD_RSA_REMOTE_SERVICE_ADMIN DFI=ON -DCMAKE_INSTALL_PREFIX=../install ..
    - make all && make deploy && make install-all
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/utils:`pwd`/framework && make test && make coverage

after_success:
    - cd ${TRAVIS_BUILD_DIR}/build
    - gem install coveralls-lcov
    - lcx="lcov --output-file=coverage.info " && for i in `find . -name "*.info.cleaned"`; do lcx+=" --add-tracefile=$i"; done && $lcx && coveralls-lcov --repo-token=9dpeTAjiGoQU5hgXFe0ezk65iu40oc3WY coverage.info

script: 
    - make all 
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/utils && make test ARGS="-V"
